name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and authenticate for scoped packages
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          scope: '@mega-utilities-company'
          auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Set package version from GitHub release
        run: |
          TAG_VERSION="${GITHUB_REF##*/}"
          TAG_VERSION="${TAG_VERSION#v}"
          echo "Setting package.json version to $TAG_VERSION"
          npm version $TAG_VERSION --no-git-tag-version

      - name: Build package
        run: npm run build

      - name: Publish package
        run: npm publish --provenance --access public
